apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ithaka-frontend-ingress
spec:
  ingressClassName: apisix  # reemplaza la anotaci√≥n vieja
  rules:
    - host: ithaka-frontend-infra.reto-ucu.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ithaka-frontend-service
                port:
                  number: 80
